### ISSUE TITLE
HorizontalAlignment = HorizontalAlignment.Fill not working

### ISSUE THREAD

**Issue by Shadowblitz16** [alternetsoft/AlternetUI#162]
The expand options are not working.

![Image](https://github.com/user-attachments/assets/7a99cbd8-6070-4876-ba51-12dcccf29335)

```cs
using Alternet.UI;
using MarioX.Engine;

namespace MarioX.Editor.Controls;

public class PaletteHeader : StackPanel
{
    public PaletteHeader(Episode episode)
    {
        var innerPanel1 = new StackPanel() {

            Orientation = StackPanelOrientation.Horizontal,
            HorizontalAlignment = HorizontalAlignment.Fill,
        };
        var nameLabel = new Label("Name:")
        {
            MinWidth = 50,
            VerticalAlignment = VerticalAlignment.Center,
        };
        var nameText    = new TextBox() {
            MinWidth = 256,
            Text = episode.GraphicBank.Palettes[0].Name,
            HorizontalAlignment = HorizontalAlignment.Fill,
            
        };

        innerPanel1.Children.Add(nameLabel);
        innerPanel1.Children.Add(nameText);
        
        var innerPanel2  = new StackPanel() {
            Orientation = StackPanelOrientation.Horizontal,
        };
        var paletteLabel = new Label("Palette:")
        {
            MinWidth = 50,
            VerticalAlignment = VerticalAlignment.Center,
        };
        var paletteBox   = new NumericUpDown() {
            Minimum = 0,
            Maximum = (int)GraphicPalette.Count,
        };
        var pageLabel = new Label("Page:")
        {
            MinWidth = 32,
            VerticalAlignment = VerticalAlignment.Center,
        };
        var pageBox      = new NumericUpDown() {
            Minimum = 0,
            Maximum = (int)GraphicColorPage.Count,
            HorizontalAlignment = HorizontalAlignment.Fill,
        };
        
        innerPanel2.Controls.Add(paletteLabel);
        innerPanel2.Controls.Add(paletteBox);
        
        innerPanel2.Controls.Add(pageLabel);
        innerPanel2.Controls.Add(pageBox);
        
        Controls.Add(innerPanel1);
        Controls.Add(innerPanel2);
        
        nameText.TextChanged += (_, __) => episode.GraphicBank.Palettes[paletteBox.Value].Name = nameText.Text;
        
    }
}
```

```cs
using System.Collections.Generic;
using Alternet.Drawing;
using Alternet.UI;
using MarioX.Editor.Controls;
using MarioX.Engine;
using Color = System.Drawing.Color;

namespace MarioX.Editor.Forms;

public class GraphicsEditor : Window
{
    private readonly Episode _episode;
    
    
    private StackPanel _palettePanel;
    private TileView _tileView;

    public GraphicsEditor(Episode episode)
    {
        _episode = episode;

        Resizable = false;

        // Width = 640;
        //
        // _palettePanel = new StackPanel();
        // _palettePanel.Dock = DockStyle.Right;
        // _palettePanel.Controls.Add(new PaletteHeader(episode));
        //
        // Controls.Add(new TileView(_episode));
        var header = new PaletteHeader(episode);
        header.Dock = DockStyle.Fill;
        Controls.Add(header);
        
    }


}
```

**Comment by Shadowblitz16** [comment]
I tried to fix it and got even more bugged out controls.

![Image](https://github.com/user-attachments/assets/f94e5482-4924-4969-a23d-652bec3e3bb9)
```cs
using System;
using Alternet.UI;
using MarioX.Engine;

namespace MarioX.Editor.Controls;

public class PaletteHeader : StackPanel
{
    public PaletteHeader(Episode episode)
    {
        Controls.Add(BuildFirstRow(episode));
        Controls.Add(BuildSecondRow(episode));
        
    }
    
    public string PaletteName  { get; set; } = string.Empty;
    public uint   PaletteIndex { get; set; } = 0;
    public uint   PageIndex    { get; set; } = 0;

    public event EventHandler? NameChanged;
    public event EventHandler? PaletteChanged;
    public event EventHandler? PageChanged;

    private StackPanel BuildFirstRow      (Episode episode)
    {
        var row       = new StackPanel() {
            Orientation = StackPanelOrientation.Horizontal,
        };
        var nameLabel = new Label("Name:") {
            VerticalAlignment   = VerticalAlignment.Center,
            HorizontalAlignment = HorizontalAlignment.Center,
        };
        var nameText  = new TextBox() {
            Text = episode.GraphicBank.Palettes[0].Name,
            HorizontalAlignment = HorizontalAlignment.Fill,
            
        };

        nameText.TextChanged += (_, _) => {
            PaletteName = nameText.Text;
            episode.GraphicBank.Palettes[PaletteIndex].Name = PaletteName;
            NameChanged?.Invoke(this, EventArgs.Empty);
        };
        row.Controls.Add(nameLabel);
        row.Controls.Add(nameText);
        return row;
    }
    private StackPanel BuildSecondRow     (Episode episode)
    {
        var row = new StackPanel() {
            Orientation = StackPanelOrientation.Horizontal,
        };
        row.Controls.Add(BuildSecondRowLeft(episode));
        row.Controls.Add(BuildSecondRowRight(episode));
        return row;
    }
    private StackPanel BuildSecondRowLeft (Episode episode)
    {
        var row          = new StackPanel() {
            Orientation = StackPanelOrientation.Horizontal,
        };
        var paletteLabel = new Label("Palette:") {
            VerticalAlignment   = VerticalAlignment.Center,
            HorizontalAlignment = HorizontalAlignment.Center,
        };
        var paletteBox   = new NumericUpDown() {
            Minimum = 0,
            Maximum = (int)GraphicPalette.Count,
        };
        paletteBox.ValueChanged += (_, _) => {
            PaletteIndex = (uint)paletteBox.Value;
            PaletteChanged?.Invoke(this, EventArgs.Empty);
        };
        
        row.Controls.Add(paletteLabel);
        row.Controls.Add(paletteBox);
        return row;
    }
    private StackPanel BuildSecondRowRight(Episode episode)
    {
        
        var row         = new StackPanel() {
            Orientation = StackPanelOrientation.Horizontal,
        };
        var pageLabel   = new Label("Page:") {
            VerticalAlignment = VerticalAlignment.Center,
            HorizontalAlignment = HorizontalAlignment.Center,
        };
        var pageBox     = new NumericUpDown() {
            Minimum = 0,
            Maximum = (int)GraphicColorPage.Count,
            HorizontalAlignment = HorizontalAlignment.Fill,
        };
        pageBox.ValueChanged += (_, _) => {
            PageIndex = (uint)pageBox.Value;
            PageChanged?.Invoke(this, EventArgs.Empty);
        };
        
        row.Controls.Add(pageLabel);
        row.Controls.Add(pageBox);
        return row;

    }
}
```

**Comment by generalloki** [comment]
It works fine. Here is screenshot and code.

![Image](https://github.com/user-attachments/assets/1994b1e1-0bc3-4b7c-9840-c690cbd294d6)

[app.zip](https://github.com/user-attachments/files/18549243/app.zip)

**Comment by Shadowblitz16** [comment]
> It works fine. Here is screenshot and code.
> 
> ![Image](https://github.com/user-attachments/assets/1994b1e1-0bc3-4b7c-9840-c690cbd294d6)
> 
> [app.zip](https://github.com/user-attachments/files/18549243/app.zip)

I tested it with the latest nuget package and got this...

![Image](https://github.com/user-attachments/assets/3f9b0812-7aef-4c70-b929-180388db8587)

**Comment by generalloki** [comment]
We did not release nugets for the latest version yet, there are still some bugs.  So there could be that Fill alignment is not completely implemented in the version of nugets that you are using. Consider using library from the github Master or wait for some time until we fix the remaining bugs and release new nugets.

As to problems with example that I provided, you need to modify there path to Alternet.UI folder (which is pulled from Master). Forgot to write about it.

**Comment by generalloki** [comment]
I have uploaded 0.9.710 nugets where this problem is fixed, so I am closing this issue.

**Comment by Shadowblitz16** [comment]
@generalloki still having issues with things takings expanding...

![Image](https://github.com/user-attachments/assets/f80f5e62-55fe-46be-8ee9-a38b76d6a419)

**Comment by generalloki** [comment]
@Shadowblitz16 
Use Grid with 2 columns and 8 rows for such kind of the layout

**Comment by Shadowblitz16** [comment]
@generalloki this does not scale well with code.
Grid requires copy and pasting code instead of making reusable components.

Here is a reusable component example which has the same result as above...
```cs
                        new Grid()
                        {
                            ColumnCount         = 1,
                            RowCount            = 8,
                            HorizontalAlignment = HorizontalAlignment.Fill,
                            Controls            =
                            {
                                CreateSpinBoxField(0, 1,"Frames:",     0, 1     , 65536, (value) => {
                                        View.GraphicBank.GetGraphic(View.GraphicId).Frames = (uint)value; 
                                        Invalidate();
                                }),
                                CreateSpinBoxField(1, 1,"FrameSpeed:", 1, 1     , 60   , (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).FrameSpeed = (uint)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(2, 1,"Width:"     , 0, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).Width = (uint)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(3, 1,"Height:"    , 0, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).Height = (uint)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(4, 1,"OffsetX:"   , 0, -32768, 32767, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).OffsetX = (int)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(5, 1,"OffsetY:"   , 0, -32768, 32767, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).OffsetY = (int)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(6, 1,"Gfx Width:" , 0, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).GfxWidth = (uint)value; 
                                    Invalidate();
                                }),
                                CreateSpinBoxField(7, 1,"Gfx Height:", 0, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).GfxHeight = (uint)value; 
                                    Invalidate();
                                }),
                            }
                        }

    private static Grid          CreateSpinBoxField(int row   , int span, string text, int value, int minimum, int maximum, Action<int> action)
    {
        return new Grid()
        {
            RowIndex   = row,
            ColumnSpan = span,
            
            ColumnCount = 2,
            RowCount    = 1,

            Controls =
            {
                CreateSpinBoxLabel(0, 1, text),
                CreateSpinBoxEdit (1, 2, value, minimum, maximum, action)
            }
        };
    }
    private static Label         CreateSpinBoxLabel(int column, int span, string text)
    {
        return new Label()
        {
            ColumnIndex = column,
            ColumnSpan = span,
            Text = text,
        };
    }
    private static NumericUpDown CreateSpinBoxEdit (int column, int span, int value, int minimum, int maximum, Action<int> action )
    {
        var spinBox = new NumericUpDown()
        {
            ColumnIndex = column,
            ColumnSpan  = span,
            Value   = value,
            Minimum = minimum,
            Maximum = maximum,
        };
        spinBox.ValueChanged += (_, _) =>
        {
            action?.Invoke(spinBox.Value);
        };
        return spinBox;
    }
```

This would be what I have to do with a grid...
```cs
                        new Grid()
                        {
                            ColumnCount         = 2,
                            RowCount            = 8,
                            HorizontalAlignment = HorizontalAlignment.Fill,
                            Controls            =
                            {
                                CreateSpinBoxLabel(0, 1, "Frames"),
                                CreateSpinBoxEdit(1,2, 1,1, 65536,  (value) => {
                                        View.GraphicBank.GetGraphic(View.GraphicId).Frames = (uint)value; 
                                        Invalidate();
                                })),
                            }
                        }

    private static Grid          CreateSpinBoxField(int row   , int span, string text, int value, int minimum, int maximum, Action<int> action)
    {
        return new Grid()
        {
            RowIndex   = row,
            ColumnSpan = span,
            
            ColumnCount = 2,
            RowCount    = 1,

            Controls =
            {
                CreateSpinBoxLabel(0, 1, text),
                CreateSpinBoxEdit (1, 2, value, minimum, maximum, action)
            }
        };
    }
    private static Label         CreateSpinBoxLabel(int column, int span, string text)
    {
        return new Label()
        {
            ColumnIndex = column,
            ColumnSpan = span,
            Text = text,
        };
    }
    private static NumericUpDown CreateSpinBoxEdit (int column, int span, int value, int minimum, int maximum, Action<int> action )
    {
        var spinBox = new NumericUpDown()
        {
            ColumnIndex = column,
            ColumnSpan  = span,
            Value   = value,
            Minimum = minimum,
            Maximum = maximum,
        };
        spinBox.ValueChanged += (_, _) =>
        {
            action?.Invoke(spinBox.Value);
        };
        return spinBox;
    }
```

**Comment by Shadowblitz16** [comment]
@generalloki It also seems like my grid does not have the correct size.
When I set my form size to the root grid size it's too small.

```
using System;
using Alternet.Drawing;
using Alternet.UI;
using MarioX.Alternet.Engine.Controls;

namespace MarioX.Alternet.Engine.Forms;

public class GraphicsForm : Window
{
    public GraphicsView View { get; } = new()
    {
        Dock = DockStyle.Fill,
    };

    public SaveFileDialog SaveFileDialog { get; } = new()
    {
        Filter = "Image files (*.png)|*.png",
    };

    public OpenFileDialog OpenFileDialog { get; } = new()
    {
        Filter = "Image files (*.png)|*.png",
    };

    public GraphicsForm()
    {
        Margin = new Thickness(4);
        Controls.Add(View);
        
        Menu     = new MainMenu() {
            Items =
            {
                new MenuItem("File")
                {
                    Items =
                    {
                        new MenuItem("Import", () =>
                        {
                            var result = OpenFileDialog.ShowDialog();
                            if (result == DialogResult.OK && !string.IsNullOrWhiteSpace(OpenFileDialog.FileName))
                            {
                                View.GraphicBank.GetGraphic(View.GraphicId).Import(OpenFileDialog.FileName);
                                Invalidate();
                            }
                        }),
                        new MenuItem("Export", () =>
                        {
                            var result = SaveFileDialog.ShowDialog();
                            if (result == DialogResult.OK && !string.IsNullOrWhiteSpace(OpenFileDialog.FileName))
                            {
                                View.GraphicBank.GetGraphic(View.GraphicId).Export(OpenFileDialog.FileName);
                                Invalidate();
                            }
                        }),
                    }
                }
            }
        };
        Title    = "Graphics";
        var grid = new Grid() {
            ColumnCount         = 2,
            RowCount            = 1,
            HorizontalAlignment = HorizontalAlignment.Fill,
            VerticalAlignment   = VerticalAlignment.Fill,
            Margin              = new Thickness(4),
            Controls            =
            {
                View,
                new GroupBox()
                {
                    Margin = new Thickness(4),
                    Text                = "Config",
                    ColumnIndex         = 1,
                    ColumnSpan          = 1,
                    RowSpan             = 1,
                    Controls            = 
                    {  
                        new Grid()
                        {

                            Margin              = new Thickness(4),
                            ColumnCount         = 2,
                            RowCount            = 8,
                            HorizontalAlignment = HorizontalAlignment.Fill,
                            VerticalAlignment = VerticalAlignment.Fill,
                            Controls            =
                            {
                                CreateSpinBoxLabel(0, 0,1,"Frames:"),
                                CreateSpinBoxEdit (1, 0,2,  1, 1     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).Frames = (uint)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 1,1,"Frames Speed:"),
                                CreateSpinBoxEdit (1, 1,2,  8, 1     , 60, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).FrameSpeed = (uint)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 2,1,"Width:"),
                                CreateSpinBoxEdit (1, 2,2,  16, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).Width = (uint)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 3,1,"Height:"),
                                CreateSpinBoxEdit (1, 3,2,  16, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).Height = (uint)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 4,1,"OffsetX:"),
                                CreateSpinBoxEdit (1, 4,2,  0, -32768     , 32767, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).OffsetX = (int)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 5,1,"OffsetY:"),
                                CreateSpinBoxEdit (1, 5,2,  0, -32768     , 32767, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).OffsetY = (int)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 6,1,"Gfx Width:"),
                                CreateSpinBoxEdit (1, 6,2,  16, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).GfxWidth = (uint)value; 
                                    Invalidate();
                                }),
                                
                                CreateSpinBoxLabel(0, 7,1,"Gfx Height:"),
                                CreateSpinBoxEdit (1, 7,2,  16, 0     , 65536, (value) => {
                                    View.GraphicBank.GetGraphic(View.GraphicId).GfxHeight = (uint)value; 
                                    Invalidate();
                                }),
                            }
                        }
                    }
                }
            }
        };

        Controls.Add(grid);
        MinWidth   = grid.MinWidth;
        MinHeight  = grid.MinHeight;
        Width      = grid.Width;
        Height     = grid.Height;
    }

    // private static Grid          CreateSpinBoxField(int row   , int span, string text, int value, int minimum, int maximum, Action<int> action)
    // {
    //     return new Grid()
    //     {
    //         RowIndex   = row,
    //         ColumnSpan = span,
    //         
    //         ColumnCount = 2,
    //         RowCount    = 1,
    //
    //         Controls =
    //         {
    //             CreateSpinBoxLabel(0, 1, text),
    //             CreateSpinBoxEdit (1, 2, value, minimum, maximum, action)
    //         }
    //     };
    // }
    private static Label         CreateSpinBoxLabel(int column, int row, int span, string text)
    {
        return new Label()
        {
            Margin = new Thickness(4),
            ColumnIndex = column,
            RowIndex = row,
            ColumnSpan = span,
            Text = text,
        };
    }
    private static NumericUpDown CreateSpinBoxEdit (int column, int row, int span, int value, int minimum, int maximum, Action<int> action )
    {
        var spinBox = new NumericUpDown()
        {
            Margin = new Thickness(4),
            ColumnIndex = column,
            RowIndex = row,
            ColumnSpan  = span,
            Value   = value,
            Minimum = minimum,
            Maximum = maximum,
        };
        spinBox.ValueChanged += (_, _) =>
        {
            action?.Invoke(spinBox.Value);
        };
        return spinBox;
    }

    
}```

This is what It looks like when I first open it.

![Image](https://github.com/user-attachments/assets/4e5aa8b0-50f1-489c-8ca6-59b83e7eca8a)

**Comment by generalloki** [comment]
@Shadowblitz16 , you need to have grid with 2 columns and 8 rows. First column is label and second column in editor.
Without any sub-grids. Something like that:

```xml
  <Grid Margin="5" RowCount="2" ColumnCount="2">
    <Label Text="Brush Color:" IsTextLocalized="true"
           Margin="0,5,15,5" Grid.Column="0" Grid.Row="0"/>
    <ColorComboBox Name="brushColorCombo" SelectedItemChanged="BrushColorCombo_Changed"
      Margin="0,0,0,10" Grid.Column="1" Grid.Row="0" />

    <Label Text="Pen Color:" IsTextLocalized="true"
           Margin="0,5,15,5" Grid.Column="0" Grid.Row="1"/>
    <ColorComboBox Name="penColorCombo" SelectedItemChanged="PenColorCombo_Changed"
      Margin="0,0,0,10" Grid.Column="1" Grid.Row="1"/>
  </Grid>

```

**Comment by Shadowblitz16** [comment]
How is that different then 1 columns with 8 rows with the rows being 2 columns and 1 row?
The issue here is not whether or not to use nested grids or not, it's the limitations of the layout system.

**Comment by generalloki** [comment]
```cs
        MinWidth   = grid.MinWidth;
        MinHeight  = grid.MinHeight;
        Width      = grid.Width; // This is incorrect
        Height     = grid.Height; // This is incorrect
```

Can you attach zip with compilable example with the problem? I will modify it and send back to you

**Comment by Shadowblitz16** [comment]
@generalloki https://drive.google.com/file/d/16npHX23I8j_q91vePA4KkLG7OdPyPa9q/view?usp=sharing
The file size was too big so I had to upload it to google drive

**Comment by Shadowblitz16** [comment]
@generalloki so this is an example of the fact nested containers don't layout properly
```cs
using System;
using System.Collections.Generic;
using System.IO;
using Alternet.Drawing;
using Alternet.UI;
using SuperX.Editor.Controls;
using SuperX.Editor.Services;

namespace SuperX.Editor;

public class GraphicWindow2 : Window
{
    GraphicView View { get; } = new();
    Grid Grid { get; }
    
    OpenFileDialog OpenFileDialog { get; } = new();
    SaveFileDialog SaveFileDialog { get; } = new();

    public GraphicWindow2()
    {
        Menu = new MainMenu()
        {
            Items =
            {
                new MenuItem("File")
                {
                    Items = 
                    {  
                        new MenuItem("Import", () =>
                        {
                            var result = OpenFileDialog.ShowDialog();
                            if (result == DialogResult.OK && File.Exists(OpenFileDialog.FileName))
                            {
                               GraphicsService.Instance.Import(View.GetId(), OpenFileDialog.FileName);
                            }
                        }),
                        //new MenuItem("Export")
                    }
                }
            }
        };

        Grid = new Grid() {
            Dock = DockStyle.Fill,
            ColumnCount = 2,
            RowCount    = 1,
            Margin = new Thickness(4),
            Controls =
            {
                View,
                new GroupBox()
                {
                    Text = "Graphics",
                    ColumnIndex = 1,
                    ColumnSpan  = 1,
                    Margin = new Thickness(4),
                    Controls =
                    {
                        new Grid()
                        {
                            ColumnCount = 1,
                            RowCount    = 10,
                            Margin = new Thickness(4),
                            Controls =
                            {
                                CreateSpinBox(0, 0, "Frames:", 1, 1, 65536, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).Frames = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 1, "FrameSpeed:", 8, 1, 60, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).FrameSpeed = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 2, "GfxWidth:",0, 1, 512, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).GfxWidth = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 3, "GfxHeight:", 0, 1, 512, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).GfxHeight = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 4, "GfxOffsetX:", 0, -256, 255, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).GfxOffsetX = (int)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 5, "GfxOffsetY:", 0, -256, 255, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).GfxOffsetY = (int)value;
                                    Invalidate();
                                }),
                                
                                
                                CreateSpinBox(0, 6, "HitWidth:", 0, 1, 512, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).HitWidth = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 7, "HitHeight:", 0, 1, 512, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).HitHeight = (uint)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 8, "HitOffsetX:", 0, -256, 255, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).HitOffsetX = (int)value;
                                    Invalidate();
                                }),
                                
                                CreateSpinBox(0, 9, "HitOffsetY:", 0, -256, 255, (value) =>
                                {
                                    GraphicsService.Instance.GetGraphic(View.GetId()).HitOffsetY = (int)value;
                                    Invalidate();
                                })
                            }
                        }
                    }
                }
            }
        };
        Controls.Add(Grid);
        View.ColumnIndex = 0;
        View.ColumnSpan = 1;
        Width  = Grid.Width;
        Height = Grid.Height;

    }


    private Control CreateSpinBox(int column, int row, string text, int value, int minimum, int maximum, Action<int> action)
    {
        return new Grid()
        {
            ColumnCount = 2,
            RowCount = 1,
            ColumnIndex = column,
            RowIndex = row,
            ColumnSpan = 1,
            Controls =
            {
                CreateSpinBoxLabel(0, 0, text),
                CreateSpinBoxField(1, 0, value, minimum, maximum, action)
            }
        };
    }

    private Control CreateSpinBoxLabel(int column, int row, string text)
    {
        return new Label()
        {
            Text = text,
            ColumnIndex = column,
            RowIndex = row,
            ColumnSpan = 1,
            Margin = new Thickness(4),
        };
    }
    private Control CreateSpinBoxField(int column, int row, int value, int minimum, int maximum, Action<int> action)
    {
        var spinBox = new NumericUpDown()
        {
            ColumnIndex = column,
            RowIndex = row,
            ColumnSpan = 2,
            Value = value,
            Minimum = minimum,
            Maximum = maximum,
            Margin = new Thickness(4),
        };
        spinBox.ValueChanged += (s, e) =>
        {
            action?.Invoke((int)spinBox.Value);
        };
        return spinBox;
    }
    
    protected override void OnResize(EventArgs e)
    {
        base.OnResize(e);
        
        // Doesn't redraw selection? bug?
        Invalidate();
    }
}
```

**Comment by generalloki** [comment]
I believe we can discuss this in 
https://github.com/alternetsoft/AlternetUI/issues/179
as we spoke there about the same project. I will post there

**Comment by Shadowblitz16** [comment]
@generalloki agreed
