### ISSUE TITLE
Seperate alignment from expanding

### ISSUE THREAD

**Issue by Shadowblitz16** [alternetsoft/AlternetUI#179]
Alignment and expanding functionality should be separated and consistent in all controls.

Basically there would be two bools called ExpandX and ExpandY, one XAlignment enum which would be None, Left, Right, Fill, and a YAlignment enum which would be None Top, Bottom, Fill,

This would allow for us to have a control take up as much space as possible and be aligned to a certain side.

This would be useful for things like labels.

Here is an example of a control with two controls inside, one on the left and one on the right. 
The left one is aligned to the left WITHOUT expanding on this x axis while the other is aligned to the right while is IS expanding on the x axis.

![Image](https://github.com/user-attachments/assets/567031ad-18ce-4fdc-ac7a-c3120ddbffdc)

**Comment by generalloki** [comment]
Thanks for the idea, we will think about this.

**Comment by Shadowblitz16** [comment]
@generalloki I would look how the godot engine does controls and containers and improve on that.

Basically Containers in godot get their size from their children's min size and there expand and alignment.
Something like a VBoxContainer would have a start padding, end padding, and seperation and would respect it's children's layout.

This could be extended to forms where forms are just containers that get their size from their children.
This would mean we wouldn't have to set a form's size explicitly.

**Comment by generalloki** [comment]
@Shadowblitz16, Right now size of the child control is calculated using their container size and specified Layout. And it seems to be fine. Also there is method that calculates size of the container depending on the size of it's children (SetSizeToContent). The layout shown on the picture in the first post is can be implemented using horizontal stack panel with second control's HorisontalAlignment=Fill. 

In order to start discussion on the layout engine improvements we need to have the example of layouts that can not be implemented using existing methods and properties.

**Comment by Shadowblitz16** [comment]
> [@Shadowblitz16](https://github.com/Shadowblitz16), Right now size of the child control is calculated using their container size and specified Layout. And it seems to be fine. Also there is method that calculates size of the container depending on the size of it's children (SetSizeToContent). The layout shown on the picture in the first post is can be implemented using horizontal stack panel with second control's HorisontalAlignment=Fill.
> 
> In order to start discussion on the layout engine improvements we need to have the example of layouts that can not be implemented using existing methods and properties.

It's currently impossible to use nested containers for things.
Some controls don't expand in certain situations.

I posted about this in the other issue, but basically horizontal/vertical layout doesn't work most of the time.
I even tried settings the column/row span in a sub grid and it doesn't play well.

**Comment by generalloki** [comment]
Please attach compilable samples which show the problem.  As far as I know we fixed all known layout related problems some time ago.

**Comment by Shadowblitz16** [comment]
@generalloki Open this and switch to the alternet version and the run it.
https://drive.google.com/file/d/1FOE6CVroWgFR2uqmO4HrXE-n2nHms0Fj/view?usp=sharing

You still can't have nested containers, and there is no way to have both align, shrink and growing.

For example here is a picture of me recreating it in godot...

![Image](https://github.com/user-attachments/assets/5634fb16-e6d1-48c9-b38e-7b745b4a2774)

This is what it looks like in alternet ui.

![Image](https://github.com/user-attachments/assets/5075b939-8a6e-4e46-8a07-09a79cf809f5)
In alternet ui for example grid get's it's sizing from rowCount and columnCount and doesn't respect the child controls size properties.

Same with stack panel.
And since alignment and expand are the same it makes it impossible to structure controls in a pretty way when it comes to trying to align children of multiple containers.

**Comment by generalloki** [comment]
I have tried sample project that you have attached. Avalonia sample when running shows an empty window.

I have modified csproj so it will include reference to the latest Alternet.UI package
```xml
<PackageReference Include="Alternet.UI" Version="0.9.710-beta" />
```

Also here is modified GraphicWindow.cs
[GraphicWindow.zip](https://github.com/user-attachments/files/19041997/GraphicWindow.zip)

When you run it, try to resize the form, controls will be sized properly. Also minimum size of the form is also specified properly.
I don't use Grid container for View and GroupBox, it's enough to set Layout to Horizontal for the Window and to specify HorizontalAlignment for the View and GroupBox.

I did not change code that aligns labels and editors, I will do it later today and attach here a new code.

**Comment by Shadowblitz16** [comment]
@generalloki the numricupanddown's are still misaligned and the window still starts too small.

![Image](https://github.com/user-attachments/assets/0a834ff2-d1ad-4a74-baa5-ab8d346b965d)

I have noticed your caclulating the window size instead of just setting it to it's content size.
That was kinda my point.

We should be able to align and expand item individually and containers should calculator their size from it's content.

**Comment by generalloki** [comment]
Parent or Controls or Children, it is the same. I personally prefer Parent.

Window start size fix:

```cs
           ClientSize = new SizeD(
            View.Width + groupBox.Width + View.Margin.Horizontal
            + groupBox.Margin.Horizontal,
            Math.Max(
                View.Height + View.Margin.Vertical,
                groupBox.Height + groupBox.Margin.Vertical));
        MinimumSize = Size;
```

As to NumericUpDown align, I will look into it and post an updated example here.

**Comment by generalloki** [comment]
As to calculation of the window size, we might add some properties to the Window (or even to Control) in order to do it automatically. Need to think about this.

**Comment by generalloki** [comment]
I have simplified an alignment and left only one grid. Here is the picrure and updated cs file.

![Image](https://github.com/user-attachments/assets/a5ea0f5f-fa37-4d5c-bd77-a3569962bf8e)

[GraphicWindowNew.zip](https://github.com/user-attachments/files/19048287/GraphicWindowNew.zip)

**Comment by Shadowblitz16** [comment]
> I have simplified an alignment and left only one grid. Here is the picrure and updated cs file.
> 
> ![Image](https://github.com/user-attachments/assets/a5ea0f5f-fa37-4d5c-bd77-a3569962bf8e)
> 
> [GraphicWindowNew.zip](https://github.com/user-attachments/files/19048287/GraphicWindowNew.zip)

You use label's instead of groupboxes?
That solves the layout problem with my form, but doesn't solve the underlying issue with nested controls.

**Comment by generalloki** [comment]
I personally don't like GroupBox as it looks different on different platforms.

Anyway, there are currently some issues with Grid and GroupBox layout in some situations, we will look into this closer to next beta release. I modified your sample in the way, so it will look good using the current build...
