### ISSUE TITLE
Linux related problems

### ISSUE THREAD

**Issue by generalloki** [alternetsoft/AlternetUI#34]
In this topic we collect Linux related issues.

**Comment by generalloki** [comment]
StackPanel in TabControl has sizing and layout problems. Also bad repaint after resize on Linux. Also grows in width without limits. First seen in ListViewSample when there were TabControl for Actions/Settings.

**Comment by generalloki** [comment]
Splitpanel problems on linux 
- mouse down on splitter does nothing (no resize) until click on inside control
- mouse cursor is bad (always is resize)

**Comment by generalloki** [comment]
ListView Mouse MouseRightButtonDown/MouseLeftButtonDown events not working Linux and macOs (seen in ControlSample)

**Comment by generalloki** [comment]
- AuiToolbar with ComboBox and TextBox. On Linux ComboBox height is different from TextBoxHeight, so toolbar is looking not good. And we need to change somehow TextBox height so it would be same as in ComboBox.
- In AuiToolbar mouse cursor on TextBox is continiously changing.
- In AuiToolbar button with arrow when it is clicked to show popup menu, this popup menu is only shown until mouse is pressed.

**Comment by generalloki** [comment]
@neoxeo reported problem in ControlsSample:

Always a problem with some samples on linux not show correctly when Samples project open after compilation : "Text Input", "Date Time" and WebBrowser" show nothing when you select them. After some minutes (1 or 2), you click again on them, and now they show content correctly.
This problem is not present on windows.

A different problem on "All samples" : show correctly just after compilation but after a resize, "full windows" and "reduced windows", it not show list but only buttons. After few minutes, it show correctly fine.

Some infos after ‌few tests if it can help you :
- problem is not always present
- problem appears in most cases when you resize windows : not present at launch but appears after full windows and reduce windows or present when launch and disappear after resize window.

**Comment by generalloki** [comment]
@neoxeo, I have made some changes in the library and ControlsSample, so it should work on your Linux properly.
Please let me know how it works. Thanks!

**Comment by neoxeo** [comment]
@generalloki 
Thanks a lot. I will be able to test this Saturday or Sunday and post here results.

**Comment by generalloki** [comment]
@neoxeo , Great! Thanks for your help. I will be waiting for the testing results.

**Comment by neoxeo** [comment]
@generalloki 
Sorry, I could not have time to do lot of tests. Here are my first results : 
There is a problem with « log » actions. There is no vertical scrollbar so we can’t see list of all actions done

Tree View : 
- When I’m in full screen window and check « Allow Label Editing », list of items disapear. If I reduce windows, list of items show again
- Same thing with « Sow Root Line » and « Show Lines » and « Show Expand Button » and « Full Row Select »
- Oder is not good Item11, Item12, Item100 are before Item1, Item2….

ListView :
- When you «Clear » and after « Add 1000 », first Item is  Item51, not Item 1

ListBox :
- When I’m in full screen window and check « Allow Multiple Selection  », list of items disapear. If I reduce windows, list of items show again.
- Same thing with « Has Border »

ComboBox :
- When I’m in full screen window and check « Allow Text Edit », ComboBox disapear. If I reduce windows, ComboBox show again.

TabControl :
Problem with "Buttons" 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/c55be18c-931b-43bf-a47a-cce3135237c8)
Solved by put to full screen window and and when I reduce windows, problem always present

Button : 
- When I’m in full screen window and check or uncheck something, Button dissapear. If I reduce windows, Button show again.

I will continue tests quickly

**Comment by generalloki** [comment]
@neoxeo , Many thanks for the help! It's bad that there are still problems on Linux. It is strange that it works fine on my Linux. Anyway, I have some ideas on what could be wrong in the code and will try it these days. In the meantime, could you also check latest versions of ControlsTest and PropertyGridSample on your Linux? Today I have updated them in master.

**Comment by neoxeo** [comment]
@generalloki 

I have made small tests with ControlsTest and PropertyGridSample on my Linux and seems to work fine.
In propertygrid, I can check or uncheck "Visible", "Enable", "Has Border" with small window or full screen window and all is OK.

With ControlsTests, actions list is not always visible when I use full screen and reduce and full and browser not in full screen. I need to switch between Webkit and webkit2 to show again action list and put them in full screen
To reproduce : 
Open ControlsTest
Select panda Sample
Click to full screen
Browser stay reduce
Click on WebKit2
Now browser 2 is in full screen
Click on WebBrowser, now it is in full screen

**Comment by generalloki** [comment]
@neoxeo , Thanks a lot! I am fixing problems that you have found and will let you know when this is done.

**Comment by neoxeo** [comment]
Hi @generalloki ,

My laptop have 2 GPU : integrated Intel and Nvidia card.

I have disable Intel and keep only Nvidia. I have installed Nvidia driver 535.

Now I have no problem with components disappear when I check or uncheck some option and when I switch to Window mode/FullScreen.

I can try to enable again Intel card to see if I can reproduce.

**Comment by generalloki** [comment]
@neoxeo , I installed Ubuntu 23 on this week and was able to reproduce bugs that you reported. Some of the bugs are already fixed, some will be fixed next week. I will let you know. Thanks for you help!

**Comment by generalloki** [comment]
- no icons on task panel for Sample projects (seen in Ubuntu 23, works fine in Ubuntu 20).
- "Search Window" for browser cannot center on screen on Linux for ControlTest.
- LinearGradientStart and other PropertyGrid items with subprops,  why they are editable? In Windows it's ok, they are readonly.

**Comment by neoxeo** [comment]
@generalloki 
Do you have installed Nvidia drivers? For me, after install it on my Ubuntu, I can't reproduce errors even if I activate both GPU cards (Intel and Nvidia).

**Comment by neoxeo** [comment]
> .

@generalloki 
Do you have installed Nvidia drivers? For me, after install it on my Ubuntu, I can't reproduce errors even if I activate both GPU cards (Intel and Nvidia).

**Comment by generalloki** [comment]
@neoxeo , problem is not related to the drivers, I can reproduce it on any computer. It will be fixed in the near future.

**Comment by neoxeo** [comment]
@generalloki 

New tests with 32bf5145c0314e11b776e65999b5134f4ad2d763 : 

PorpertyGridSample (very impressive job, fantastic !!!) : 
Slider is very slow

EmployeeFormSample : 
problem with ComboBox « State » when you click on this it Open and Close immediatly. You need to stay mise button down to chosse a value

**Comment by generalloki** [comment]
@neoxeo , Issue with PropertyGrid and Slider is known. PropertyGrid updates itself when slider position is changed. Currently not only changed property is updated, but all other too. So its slow.  This will be improved in one of the future builds. As to ComboBox, I will check this closer to the new build release. Thanks a lot for your help.

**Comment by generalloki** [comment]
AnimationPlayer works fine in Ubuntu 20 but doesn't wotk in Ubuntu 23

**Comment by neoxeo** [comment]
@generalloki 

On Ubuntu, in Slider sample, trick shown even if None is select : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/608ace59-e226-45f7-b127-c919202eb4e8)

**Comment by neoxeo** [comment]
@generalloki 

Version : bc1c2d89825c0858334e8b757cab027fe9fc54c9

TabControl sample, when you change size Full screen/reduce Window, problem with Button and Tab places : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/e74a1763-58a0-41c1-aa23-2ed3b14bf893)

**Comment by generalloki** [comment]
@neoxeo 👍 

We have improved TabControl behavior on the Linux in the 0.9.406 but it's not complete yet.  Problems with strange behavior of TabControl and other controls when the form is maximized on Linux are not fixed yet. I will update this issue when it's fixed
completely.

As to slider behavior, I will investigate this but it seems to be a wxWidget problem, we pass tick style correctly. I will update this issue when I have more details.

**Comment by generalloki** [comment]
@neoxeo , about Slider and TickStyle under Linux. I have added additional method Slider.ClearTicks(). The usual way (assigning TickStyle to None) seems not working in WxWidgets under Linux.

**Comment by generalloki** [comment]
AnimationPlayer not working on Ubuntu 23 but works ok on Ubuntu 20

**Comment by generalloki** [comment]
Current situation with Linux support:

- Maximize of the form ruins layout. This is not fixed. 
- TabControl seems to be fixed and working fine. @neoxeo, please let me know if there are problems with TabControl in your configuration.
- AnimationPlayer not working on Ubuntu 23 but works ok on Ubuntu 20.
- no icons on task panel for Sample projects (seen in Ubuntu 23, works fine in Ubuntu 20).
- LinearGradientStart and other PropertyGrid items with subprops, why they are editable? In Windows it's ok, they are readonly.

**Comment by neoxeo** [comment]
@generalloki 

Problem with TabControl seems to be not totaly resolved with last 504 commit.

**How to reproduce it :** 
1. Run SamplesControl
2. Select tabPage
3. Reduce size to obtain this : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/014bc2f8-1360-4419-976d-0b3f54249640)

4. Increase size : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/a4730f10-e6ac-45fa-aa8f-8937045207ff)

**If you reduce Window and show it again, problem have disapear. It seems that you need to add "refresh" after a resize event.**

**Comment by generalloki** [comment]
@neoxeo , I have fixed Window Maximize problem and TabControl behaviour. Could you please check this and let me know how it  works with your configuration? Thanks!

**Comment by neoxeo** [comment]
@generalloki 

I confirm issue Window Maximize problem and TabControl solved with my configuration.

Thanks !

**Comment by generalloki** [comment]
@neoxeo , Thanks a lot for your help. It is great that these problems finally solved

**Comment by Shadowblitz16** [comment]
```
Exception has occurred: CLR/System.TypeInitializationException
An unhandled exception of type 'System.TypeInitializationException' occurred in Alternet.UI.dll: 'The type initializer for 'Alternet.UI.Application' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.DllNotFoundException : Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libAlternet.UI.Pal: cannot open shared object file: No such file or directory
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
   at Alternet.UI.Native.NativeApiProvider.Initialize()
   at Alternet.UI.Native.WebBrowser.NativeApi..cctor()
```
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-15-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: RENOIR
```

**Comment by neoxeo** [comment]
@Shadowblitz16 

Did you have tried to run Install.sh to be sure you have all prerequisites and if compile is ok ?

**Comment by Shadowblitz16** [comment]
@neoxeo I just tried the `Install.Scripts/Ubuntu.Install.Packages.sh` detailed here https://docs.alternet-ui.com/tutorials/hello-world/command-line/hello-world-command-line.html

I still get a error.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Alternet.UI.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.Native.WebBrowser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NativeApi' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libAlternet.UI.Pal: cannot open shared object file: No such file or directory
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
```

**Comment by generalloki** [comment]
@Shadowblitz16 , 

If you use Alternet.UI nuget in the application, the problem could be in Alternet.UI nuget working incorrectly under Linux (it may do not copy Alternet.UI.PAL dll to the application folder). If there are no Alternet.UI.Pal.so in the app BIN folder after the build, this is the case. I will investigate this and post results here. 

As to problem with Install.sh execution (error in CommonProcs.cs): I beleive if you install Net 8 it will run fine after that.

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 ,
> 
> If you use Alternet.UI nuget in the application, the problem could be in Alternet.UI nuget working incorrectly under Linux (it may not copy Alternet.UI.PAL dll to the application folder). If there are no Alternet.UI.Pal.so in the app BIN folder after the build, this is the case. I will investigate this and post results here.
> 
> As to problem with Install.sh execution (error in CommonProcs.cs): I beleive if you install Net 8 it will run fine after that.

I can't install .net 8 I'm on kubuntu 22.04 and I don't want leave the LTS version.

**Comment by generalloki** [comment]
@Shadowblitz16 , I have checked sample project with nugets under Ubuntu 23 and it works fine.

1. Run: Install.Scripts/Ubuntu.Install.Packages.sh
2. Run: dotnet new install Alternet.UI.Templates
3. Run: dotnet new alternet-ui
4. Run: dotnet run

Details in:
https://docs.alternet-ui.com/tutorials/hello-world/command-line/hello-world-command-line.html

Could you please run these steps on your pc? How it works?

**Comment by generalloki** [comment]
@Shadowblitz16 

I have installed Kubuntu and reproduced the problem. When I find the solution I will post here an update. Thanks for the reported issue.

**Comment by generalloki** [comment]
Current situation with Linux support:

Top:

- Popups not working properly on Linux
- On Kubuntu application can not start as PAL cannot be loaded

Other issues:

- AnimationPlayer not working on Ubuntu 23 but works ok on Ubuntu 20.
- no icons on task panel for Sample projects (seen in Ubuntu 23, works fine in Ubuntu 20).
- LinearGradientStart and other PropertyGrid items with subprops, why they are editable? In Windows it's ok, they are readonly.
- ListView MouseRightButtonDown/MouseLeftButtonDown events not working Linux and macOs (seen in ControlSample)
- Slider works slow in PropertyGridDemo

**Comment by generalloki** [comment]
@Shadowblitz16 ,

I have updated Master with the new version. Now you can run Install.NoNet8.sh and it will work fine on Kubuntu without Net 8
installed. Also you need to remove net 8 in TargetFrameworks.props files:
===========
<b>STEP 4.</b> (Optional) Specify target frameworks:
You can modify list of target frameworks in files
"Source\Samples\CommonData\TargetFrameworks.props" and "Source\Version\TargetFrameworks.props".
This will speed up the build process.
===========

**Comment by Shadowblitz16** [comment]
@generalloki nope. still errors.
```
shadowblitz16@Kubuntu:~/Documents/Source/cs/SMB-Classic$ dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Alternet.UI.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.Native.WebBrowser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NativeApi' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libAlternet.UI.Pal: cannot open shared object file: No such file or directory
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
   at Alternet.UI.Native.NativeApiProvider.Initialize()
   at Alternet.UI.Native.WebBrowser.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.WebBrowser.NativeApi.WebBrowser_SetEventCallback_(WebBrowserEventCallbackType callback)
   at Alternet.UI.Native.WebBrowser.SetEventCallback()
   at Alternet.UI.Native.WebBrowser..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.WebBrowser.GetBackendOS()
   at Alternet.UI.WebBrowser.GetBackendOS()
   at Alternet.UI.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Application..ctor()
   at SMB_Classic.Program.Main(String[] args) in /home/shadowblitz16/Documents/Source/cs/SMB-Classic/Program.cs:line 11
```

I even created a new project after I installed alternet ui with `Install.NoNet8.sh `

**Comment by generalloki** [comment]
@Shadowblitz16 , There is something with your project. Maybe it uses v0.9.503 nugets. 
I have created special project which I successfully tested on Kubuntu.
It is located in AlternetUI\Source\Tests\UseLocalPackages\ folder
First you run Download.505.sh, it downloads v0.9.505 nugets to LocalPackages subfolder.
After that you run run.sh.

If you attach here your csproj file, I will be able to tell what is wrong with it.

**Comment by Shadowblitz16** [comment]
Well when trying to fix this I uninstalled dotnet 7.0 and found out how to install 8.0 which didn't work so I removed everything and installed dotnet 6.0

and it works...
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/041f5917-3a07-4431-be0b-f638b445b37c)


Now that I have dotnet 8.0 sdk how would I run it with that?

**Comment by generalloki** [comment]
@Shadowblitz16 ,

You need to install all possible SDKs, 6,7,8 before running Install.sh. There is no need to uninstall any sdk as they can work together.

**Comment by Shadowblitz16** [comment]
@generalloki I got Install.sh to run after installling dotnet 6,7, and 8 but my project still does not run.
```
shadowblitz16@Kubuntu:~/Documents/Source/cs/SMBX-R$ dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Alternet.UI.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.Native.WebBrowser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NativeApi' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libAlternet.UI.Pal: cannot open shared object file: No such file or directory
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
   at Alternet.UI.Native.NativeApiProvider.Initialize()
   at Alternet.UI.Native.WebBrowser.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.WebBrowser.NativeApi.WebBrowser_SetEventCallback_(WebBrowserEventCallbackType callback)
   at Alternet.UI.Native.WebBrowser.SetEventCallback()
   at Alternet.UI.Native.WebBrowser..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.WebBrowser.GetBackendOS()
   at Alternet.UI.WebBrowser.GetBackendOS()
   at Alternet.UI.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Application..ctor()
   at SMBX_R.Program.Main(String[] args) in /home/shadowblitz16/Documents/Source/cs/SMBX-R/Program.cs:line 11```

**Comment by generalloki** [comment]
Could you post here the project? Or some project which shows the error?

**Comment by Shadowblitz16** [comment]
@generalloki 
[SMBX-R.zip](https://github.com/alternetsoft/AlternetUI/files/14254070/SMBX-R.zip)

**Comment by generalloki** [comment]
@Shadowblitz16 ,
As I mentioned above, the problem is that templates use v0.9.503 nugets
which do not work on Kubuntu.
I have created special project which I successfully tested on Kubuntu.
It is located in AlternetUI\Source\Tests\UseLocalPackages\ folder
First you run Download.505.sh, it downloads v0.9.505 nugets to LocalPackages subfolder.
After that you run run.sh.

So, current solution is to use project template from the AlternetUI\Source\Tests\UseLocalPackages\ folder.

**Comment by generalloki** [comment]
Current situation with Linux support:

Top:

- FIXED. Popups not working properly on Linux
- FIXED. On Kubuntu application can not start as PAL cannot be loaded
- TabControl second and more pages are not visible.
- DateTimePopup is shown in bad location under Ubuntu 23 (Linux window manager doesn't allow to position top window anymore) 

Other issues:

- AnimationPlayer not working on Ubuntu 23 but works ok on Ubuntu 20.
- no icons on task panel for Sample projects (seen in Ubuntu 23, works fine in Ubuntu 20).
- LinearGradientStart and other PropertyGrid items with subprops, why they are editable? In Windows it's ok, they are readonly.
- ListView MouseRightButtonDown/MouseLeftButtonDown events not working Linux and macOs (seen in ControlSample)
- Slider works slow in PropertyGridDemo

**Comment by Shadowblitz16** [comment]
@generalloki I installed pal though nuget and it can't find the library...
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/87aca6b7-b06d-4409-82f3-d9bb64ea1cef)
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/43558c7f-29d5-42c2-8b07-a0a564f4f502)

but it is here...
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/0e1897bb-0812-4b3a-8d5c-a813cf3b1a1d)

**Comment by generalloki** [comment]
@Shadowblitz16, thanks for the report 

Please get latest version from the master and call Install.sh. Use version from master in you development. We did not update nugets for some time, this problem was fixed after we released nugets. I will post a message here when new beta is ready and nugets are updated.

**Comment by Shadowblitz16** [comment]
@generalloki thats what I did but I still get it.
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/e786089a-fb2a-4f66-b042-50cac24e7da4)


I did the following...
- pulled from master
- ran Ubuntu.Install.Packages.sh
- run Install.sh
- created new project with `dotnet new alternet-ui`

**Comment by generalloki** [comment]
@Shadowblitz16 

Now I understand where problem is. Command "dotnet new alternet-ui" creates project which uses nugets. So it is not compatible with version from master. To create project that is compartible with it, you need to use MinMasterTemplate from 
https://github.com/alternetsoft/AlternetUI/tree/master/Install.Scripts/MinMasterTemplate
see readme.md in that folder. I think we will have a better solution and I will post it here when it is available

**Comment by Shadowblitz16** [comment]
@generalloki maybe using a actual template we can install instead of a project would help.

**Comment by generalloki** [comment]
@Shadowblitz16 
I uploaded new nugets to github
https://github.com/alternetsoft/AlternetUI/releases/tag/0.9.613-beta

We will do final tests and if everything is ok, upload them to nuget.org. After that you will be able to use 
dotnet new alternet-ui
as described in
https://docs.alternet-ui.com/tutorials/hello-world/command-line/hello-world-command-line.html

I will post here an update when it is done.

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 I uploaded new nugets to github https://github.com/alternetsoft/AlternetUI/releases/tag/0.9.613-beta
> 
> We will do final tests and if everything is ok, upload them to nuget.org. After that you will be able to use dotnet new alternet-ui as described in https://docs.alternet-ui.com/tutorials/hello-world/command-line/hello-world-command-line.html
> 
> I will post here an update when it is done.

@generalloki I downloaded the ui and pal nugets from that release and they still crash on run..
```
file:///home/shadowblitz16/Downloads/Alternet.UI.0.9.613-beta.nupkg
file:///home/shadowblitz16/Downloads/Alternet.UI.Pal.0.9.613-beta.nupkg

```

![image](https://github.com/user-attachments/assets/ca1953c9-7f9a-4d78-95ea-9a5b9266fcd5)

**Comment by generalloki** [comment]
@Shadowblitz16 
There were linux related bug in 0.9.613 and it is fixed in the new build.
https://github.com/alternetsoft/AlternetUI/releases/tag/0.9.618-beta

I will test new build and post here an update on whether it works fine with new nugets on Linux.

**Comment by generalloki** [comment]
@Shadowblitz16, I have checked the latest build and it still has an error when running with nugets on Linux.
I will post here an update when it is fixed.

**Comment by generalloki** [comment]
@Shadowblitz16
The problem is that Alternet.Ui.Pal.so compiled on another Linux machine can not be loaded due to some incompatibilities with other Linux libraries. This happens because wxWidgets used in Alternet.UI compiles differently on different Linux versions. I am investigating the problem and will try to find a fix for that.

**Comment by generalloki** [comment]
@Shadowblitz16
The reason Alternet.Ui.Pal.so is not loaded properly is that it is compiled on Ubuntu 20
and requires the following libraries in order to run:

libwebkit2gtk-4.0.so.37
libjavascriptcoregtk-4.0.so.18
libtiff.so.5

On Ubuntu 24 and other modern Linux systems these libraries are absent (they have new versions of these libraries installed).
The solution is to build Alternet.Ui.Pal.so on the modern Linux and to stop Ubuntu 20 support.
I will upload a new build to github on these days and post here an update on the issue.

**Comment by Shadowblitz16** [comment]
@generalloki you can't support both? 
Is there no way to conditionally check what system they are running?

**Comment by Shadowblitz16** [comment]
@generalloki can you upload this to nuget or are you still working on it?

**Comment by generalloki** [comment]
@Shadowblitz16 
We don't have the final 0.9.6x build yet. We will post a new build in the beginning of the week to github. And if it works fine, nuget.org will be updated. In the meantime, you can download any build from github and use nugets locally.

You can create "LocalPackages" sub-folder in the solution folder, place nugets to this sub-folder
and create "NuGet.config" file like this.

```xml
<?xml version="1.0" encoding="utf-8"?>
  <configuration>
    <packageSources>
      <add key="LocalPackages" value="./LocalPackages" />
    </packageSources>
    <activePackageSource>
      <!-- this tells that all of them are active -->
      <add key="All" value="(Aggregate source)" />
    </activePackageSource>
 </configuration>
```
See an example in 
AlternetUI\Publish\PublicFiles\Samples\

**Comment by generalloki** [comment]
@Shadowblitz16 

We have uploaded new build to
https://github.com/alternetsoft/AlternetUI/releases

**Comment by generalloki** [comment]
@Shadowblitz16 

We have updated nugets on nuget.org with the latest build

**Comment by Shadowblitz16** [comment]
@generalloki still error on run...
```bash
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/NewSMBX
Unhandled exception. Critical
System.TypeInitializationException: The type initializer for 'Alternet.UI.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.WxApplicationHandler' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.Native.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NativeApi' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
libwebkit2gtk-4.1.so.0: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/Alternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/Alternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/libAlternet.UI.Pal: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libAlternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/libAlternet.UI.Pal: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Alternet.UI.Native.NativeApiProvider.<ImportResolver>g__Fn|12_1(<>c__DisplayClass12_0&)
   at Alternet.UI.Native.NativeApiProvider.ImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
   at Alternet.UI.Native.NativeApiProvider.Initialize()
   at Alternet.UI.Native.Application.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.Application.NativeApi.Application_SetEventCallback_(ApplicationEventCallbackType callback)
   at Alternet.UI.Native.Application.SetEventCallback()
   at Alternet.UI.Native.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.Application.GetEventIdentifiers(Int32[] eventIdentifiers)
   at Alternet.UI.WxApplicationHandler..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.WxApplicationHandler..ctor()
   at Alternet.UI.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Application..ctor(IApplicationHandler handler)
   at NewSMBX.Program.Main(String[] args) in /home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/Program.cs:line 12
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
kf.sonnet.clients.hspell: HSpellDict::HSpellDict: Init failed

Process finished with exit code 134.
```

**Comment by generalloki** [comment]
@Shadowblitz16 

Error says libwebkit2gtk-4.1.so.0 not found.

In order to check what libwebkit* packages are installed, run ```sudo apt list libwebkit*```

In order to install required package, run ```sudo apt-get install -y libwebkit2gtk-4.1-dev``` 
This will fix the problem.

In order to check on other required packages for Alternet.UI.Pal, run ```ldd Alternet.UI.Pal.so```

If your linux doesn't support libwebkit2gtk-4.1 installation, you need to update it to the new version.

What linux do you use?

**Comment by Shadowblitz16** [comment]
@generalloki I just updated my linux to kubuntu 24.04
I did `sudo apt-get install -y libwebkit2gtk-4.1-dev` and it seemed to work then I did `ldd Alternet.UI.Pal.so` and got this..
```bash
shadowblitz16@shadowblitz16-desktop:~/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native$ ldd Alternet.UI.Pal.so
        linux-vdso.so.1 (0x00007fffd0bca000)
        libwebkit2gtk-4.1.so.0 => /lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0 (0x0000722c84c00000)
        libjavascriptcoregtk-4.1.so.0 => /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0 (0x0000722c83000000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x0000722c894c3000)
        libSM.so.6 => /lib/x86_64-linux-gnu/libSM.so.6 (0x0000722c8a7ec000)
        libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x0000722c8a7a3000)
        libgspell-1.so.2 => not found
        libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x0000722c82800000)
        libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x0000722c82705000)
        libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x0000722c8a790000)
        libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x0000722c825c1000)
        libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x0000722c8a760000)
        libXtst.so.6 => /lib/x86_64-linux-gnu/libXtst.so.6 (0x0000722c8a758000)
        libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x0000722c8a73d000)
        libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x0000722c84b95000)
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x0000722c8a6ec000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x0000722c89498000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x0000722c82fc8000)
        libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x0000722c8253e000)
        libtiff.so.6 => /lib/x86_64-linux-gnu/libtiff.so.6 (0x0000722c824b1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x0000722c8947c000)
        libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x0000722c822e1000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x0000722c8227e000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x0000722c82135000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000722c81e00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000722c81d17000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000722c82108000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000722c81a00000)
        libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x0000722c818dd000)
        libicui18n.so.74 => /lib/x86_64-linux-gnu/libicui18n.so.74 (0x0000722c81400000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x0000722c81c37000)
        libicuuc.so.74 => /lib/x86_64-linux-gnu/libicuuc.so.74 (0x0000722c81000000)
        libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x0000722c817d0000)
        libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x0000722c820de000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x0000722c8121e000)
        libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x0000722c80e98000)
        libxslt.so.1 => /lib/x86_64-linux-gnu/libxslt.so.1 (0x0000722c8209d000)
        liblcms2.so.2 => /lib/x86_64-linux-gnu/liblcms2.so.2 (0x0000722c8176e000)
        libwoff2dec.so.1.0.2 => /lib/x86_64-linux-gnu/libwoff2dec.so.1.0.2 (0x0000722c8946d000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x0000722c80dcc000)
        libharfbuzz-icu.so.0 => /lib/x86_64-linux-gnu/libharfbuzz-icu.so.0 (0x0000722c84b90000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x0000722c80c84000)
        libgstallocators-1.0.so.0 => /lib/x86_64-linux-gnu/libgstallocators-1.0.so.0 (0x0000722c82093000)
        libgstapp-1.0.so.0 => /lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x0000722c8207d000)
        libgstbase-1.0.so.0 => /lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x0000722c80bff000)
        libgstreamer-1.0.so.0 => /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x0000722c80aac000)
        libgstpbutils-1.0.so.0 => /lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x0000722c80a69000)
        libgstaudio-1.0.so.0 => /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x0000722c809e4000)
        libgsttag-1.0.so.0 => /lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x0000722c809a3000)
        libgstvideo-1.0.so.0 => /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x0000722c808ce000)
        libgstgl-1.0.so.0 => /lib/x86_64-linux-gnu/libgstgl-1.0.so.0 (0x0000722c8083b000)
        libgstfft-1.0.so.0 => /lib/x86_64-linux-gnu/libgstfft-1.0.so.0 (0x0000722c81c2c000)
        libwebpdemux.so.2 => /lib/x86_64-linux-gnu/libwebpdemux.so.2 (0x0000722c84b89000)
        libwebp.so.7 => /lib/x86_64-linux-gnu/libwebp.so.7 (0x0000722c807c0000)
        libsoup-3.0.so.0 => /lib/x86_64-linux-gnu/libsoup-3.0.so.0 (0x0000722c80727000)
        libenchant-2.so.2 => /lib/x86_64-linux-gnu/libenchant-2.so.2 (0x0000722c81c1f000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x0000722c81c18000)
        libsecret-1.so.0 => /lib/x86_64-linux-gnu/libsecret-1.so.0 (0x0000722c806c8000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x0000722c81758000)
        libhyphen.so.0 => /lib/x86_64-linux-gnu/libhyphen.so.0 (0x0000722c81750000)
        libwayland-server.so.0 => /lib/x86_64-linux-gnu/libwayland-server.so.0 (0x0000722c806b2000)
        libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x0000722c8120e000)
        libmanette-0.2.so.0 => /lib/x86_64-linux-gnu/libmanette-0.2.so.0 (0x0000722c80682000)
        libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x0000722c80662000)
        libgbm.so.1 => /lib/x86_64-linux-gnu/libgbm.so.1 (0x0000722c80651000)
        libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x0000722c8063a000)
        /lib64/ld-linux-x86-64.so.2 (0x0000722c8a80f000)
        libatomic.so.1 => /lib/x86_64-linux-gnu/libatomic.so.1 (0x0000722c80630000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x0000722c80607000)
        libICE.so.6 => /lib/x86_64-linux-gnu/libICE.so.6 (0x0000722c805eb000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x0000722c805e1000)
        libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x0000722c805c3000)
        libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x0000722c805b7000)
        libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x0000722c805a4000)
        libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x0000722c80568000)
        libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x0000722c80560000)
        libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x0000722c80556000)
        libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x0000722c80551000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x0000722c8053d000)
        libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x0000722c80531000)
        libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x0000722c8052c000)
        libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x0000722c80527000)
        libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x0000722c8051a000)
        libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x0000722c80515000)
        libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x0000722c80509000)
        libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x0000722c804fa000)
        libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x0000722c804f5000)
        libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x0000722c80446000)
        libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x0000722c80439000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x0000722c8037f000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x0000722c8034d000)
        libLerc.so.4 => /lib/x86_64-linux-gnu/libLerc.so.4 (0x0000722c802c6000)
        libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x0000722c802b6000)
        libdeflate.so.0 => /lib/x86_64-linux-gnu/libdeflate.so.0 (0x0000722c802a1000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x0000722c80254000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x0000722c80227000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x0000722c8021b000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x0000722c80181000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x0000722c80172000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x0000722c80150000)
        libicudata.so.74 => /lib/x86_64-linux-gnu/libicudata.so.74 (0x0000722c7e200000)
        libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x0000722c8012a000)
        libwoff2common.so.1.0.2 => /lib/x86_64-linux-gnu/libwoff2common.so.1.0.2 (0x0000722c80125000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x0000722c80115000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x0000722c80101000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x0000722c800dc000)
        libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x0000722c800c1000)
        libdw.so.1 => /lib/x86_64-linux-gnu/libdw.so.1 (0x0000722c8000d000)
        liborc-0.4.so.0 => /lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x0000722c7e14e000)
        libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x0000722c7ff84000)
        libEGL.so.1 => /lib/x86_64-linux-gnu/libEGL.so.1 (0x0000722c7ff72000)
        libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x0000722c7ff6d000)
        libgudev-1.0.so.0 => /lib/x86_64-linux-gnu/libgudev-1.0.so.0 (0x0000722c7ff60000)
        libsharpyuv.so.0 => /lib/x86_64-linux-gnu/libsharpyuv.so.0 (0x0000722c7e144000)
        libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x0000722c7e130000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x0000722c7e0dc000)
        libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x0000722c7e0b1000)
        libevdev.so.2 => /lib/x86_64-linux-gnu/libevdev.so.2 (0x0000722c7e093000)
        libxcb-randr.so.0 => /lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x0000722c7e080000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x0000722c7e07a000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x0000722c7e072000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x0000722c7e05c000)
        libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x0000722c7e022000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x0000722c7dfd1000)
        libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x0000722c7dfc8000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x0000722c7df8d000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x0000722c7df6a000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x0000722c7df4a000)
        libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x0000722c7de92000)
        libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x0000722c7de5f000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x0000722c7de2c000)
        libunistring.so.5 => /lib/x86_64-linux-gnu/libunistring.so.5 (0x0000722c7dc7f000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x0000722c7dc5b000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x0000722c7db92000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x0000722c7db66000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x0000722c7db60000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x0000722c7db53000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x0000722c7db42000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x0000722c7db3b000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x0000722c7db28000)
```

when I run again I get this...
```bash
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/NewSMBX
Unhandled exception. Critical
System.TypeInitializationException: The type initializer for 'Alternet.UI.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.WxApplicationHandler' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Alternet.UI.Native.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NativeApi' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Alternet.UI.Pal' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
libgspell-1.so.2: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/Alternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/Alternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/libAlternet.UI.Pal.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/Alternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/runtimes/linux-x64/native/libAlternet.UI.Pal: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libAlternet.UI.Pal: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/bin/Debug/net8.0/libAlternet.UI.Pal: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Alternet.UI.Native.NativeApiProvider.<ImportResolver>g__Fn|12_1(<>c__DisplayClass12_0&)
   at Alternet.UI.Native.NativeApiProvider.ImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Alternet.UI.Native.NativeApiProvider.SetExceptionCallback(NativeExceptionCallbackType unhandledExceptionCallback, NativeExceptionCallbackType caughtExceptionCallback)
   at Alternet.UI.Native.NativeApiProvider.Initialize()
   at Alternet.UI.Native.Application.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.Application.NativeApi.Application_SetEventCallback_(ApplicationEventCallbackType callback)
   at Alternet.UI.Native.Application.SetEventCallback()
   at Alternet.UI.Native.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Native.Application.GetEventIdentifiers(Int32[] eventIdentifiers)
   at Alternet.UI.WxApplicationHandler..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.WxApplicationHandler..ctor()
   at Alternet.UI.Application..cctor()
   --- End of inner exception stack trace ---
   at Alternet.UI.Application..ctor(IApplicationHandler handler)
   at NewSMBX.Program.Main(String[] args) in /home/shadowblitz16/Documents/Source/cs/NewSMBX/NewSMBX/Program.cs:line 12
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
kf.sonnet.clients.hspell: HSpellDict::HSpellDict: Init failed

Process finished with exit code 134.
```

**Comment by generalloki** [comment]
@Shadowblitz16 

Same problem:  libgspell-1.so.2 is not found

It is solved using such command ```sudo apt-get install -y libgspell-1```

All the required packages are also installed by the Ubuntu.Install.Packages.sh script
It is here
https://github.com/alternetsoft/AlternetUI/blob/master/Install.Scripts/Ubuntu.Install.Packages.sh

**Comment by Shadowblitz16** [comment]
@generalloki That fixed it I forgot that part and when I updated I actually installed a new os so thankyou

**Comment by generalloki** [comment]
Current situation with Linux:

Top:

- DateTimePopup is shown in bad location under Ubuntu 23 (Linux window manager doesn't allow to position top window anymore).

Other bugs:

- AnimationPlayer not working on Ubuntu 23 but works ok on Ubuntu 20.
- no icons on task panel for Sample projects (seen in Ubuntu 23, works fine in Ubuntu 20).
- LinearGradientStart and other PropertyGrid items with subprops, why they are editable? In Windows it's ok, they are readonly.
- ListView MouseRightButtonDown/MouseLeftButtonDown events not working Linux and macOs (seen in ControlSample)
- Slider works slow in PropertyGridDemo

Ideas: 

- We need to test on  Debian, Fedora, RedHat, SUSE.

**Comment by Shadowblitz16** [comment]
idk if I am doing something wrong but I tried to setup a MainWindow in rider.

MainWindow.uixml
```xml
<Window xmlns="http://schemas.alternetsoft.com/ui/2021"
        xmlns:x="http://schemas.alternetsoft.com/ui/2021/uixml"
        x:Class="EditorX.Editor.Forms.MainWindow"
        Title="Editor X"
        xmlns:drawing="clr-namespace:Alternet.Drawing;assembly=Alternet.UI"
        MinWidth="500" MinHeight="200">>
    <Window.Menu>
      <MainMenu>
        <MenuItem Text="_File">
          <MenuItem Text="New..." Name="newMenuItem" Command="{Binding FileNewCommand}"/>
          <MenuItem Text="-"/>
          <MenuItem Text="Open..." Name="openMenuItem" Command="{Binding FileOpenCommand}"/>
          <MenuItem Text="-"/>
          <MenuItem Text="Save" Name="saveMenuItem" Command="{Binding FileSaveCommand}"/>
          <MenuItem Text="Save As..." Name="saveAsMenuItem" Command="{Binding FileSaveAsCommand}"/>
          <MenuItem Text="-"/>
          <MenuItem Text="Exit" Name="exitMenuItem" Click="FileExitCommand" />
        </MenuItem>
      </MainMenu>
    </Window.Menu>
</Window>
```

MainWindow.uixml.cs
```cs
using Alternet.Drawing;
using Alternet.UI;
using EditorX.Engine.Formats;
using Newtonsoft.Json;
using Newtonsoft.Json.Bson;

namespace EditorX.Editor.Forms;

public partial class MainWindow : Window
{
    public Quest? Quest { get; set; }
    public string Recent { get; set; } =string.Empty;
    
    public Command FileNewCommand    { get; }
    public Command FileOpenCommand   { get; }
    public Command FileSaveCommand   { get; }
    public Command FileSaveAsCommand { get; }
    public Command FileExitCommand   { get; }
    
    public MainWindow()
    {
        InitializeComponent();

        DataContext       = this;
        FileNewCommand    = new Command(o => {
            Quest = new Quest();
        });
        FileOpenCommand   = new Command(o => {
            OpenFileDialog.Default.Filter = "Quest files(qst.*)|qst.*";
            var result = OpenFileDialog.Default.ShowDialog();
            if (result == DialogResult.OK)
            {
                using var stream = File.OpenRead(SaveFileDialog.Default.FileName);
                using var reader = new BsonDataReader(stream);
                var serializer   = new JsonSerializer();
                Quest = serializer.Deserialize<Quest>(reader);
                Recent = SaveFileDialog.Default.FileName;
            }
        });
        FileSaveCommand   = new Command(o => {
            using var stream = File.OpenWrite(Recent);
            using var reader = new BsonDataWriter(stream);
            var serializer   = new JsonSerializer();
            serializer.Serialize(reader, Quest);
        });
        FileSaveAsCommand = new Command(o => {
            OpenFileDialog.Default.Filter = "Quest files(qst.*)|qst.*";
            var result = SaveFileDialog.Default.ShowDialog();
            if (result == DialogResult.OK)
            {
                using var stream = File.OpenWrite(SaveFileDialog.Default.FileName);
                using var reader = new BsonDataWriter(stream);
                var serializer   = new JsonSerializer();
                serializer.Serialize(reader, Quest);
                Recent = SaveFileDialog.Default.FileName;
            }
        });
        FileExitCommand   = new Command(o => {
            Close();
        });
    }
}
```
```bash
Unhandled exception. XamlX.XamlParseException: Unable to resolve type Binding from namespace http://schemas.alternetsoft.com/ui/2021 Line 3, position 94.
   at Alternet.UI.UixmlLoader.LoadExistingEx(Stream xamlStream, Object existingObject, Flags flags, String resName)
   at Alternet.UI.UixmlLoader.LoadExisting(String resName, Object existingObject)
   at EditorX.Editor.Forms.MainWindow.InitializeComponent() in /home/shadowblitz16/Documents/Source/cs/EditorX/EditorX/obj/Debug/net8.0/UIXml/Editor/Forms/MainWindow.g.cs:line 33
   at EditorX.Editor.Forms.MainWindow..ctor() in /home/shadowblitz16/Documents/Source/cs/EditorX/EditorX/Editor/Forms/MainWindow.uixml.cs:line 22
   at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/Source/cs/EditorX/EditorX/Program.cs:line 7

Process finished with exit code 134.

```

**Comment by generalloki** [comment]
@Shadowblitz16 , Bindings are currently turner off. So "{Binding FileNewCommand}" is not possible. If you need to use commands, I posted an example in #125.

**Comment by generalloki** [comment]
I am closing this issue, most of the Linux related bugs were already fixed. If there will be any new problems, we need separate issue for the each problem.
